### ISSUE TITLE
Want to change the color for PHP (#ab7967) but I can't seem to make it take

### ISSUE THREAD

**Issue by b-d-m-p** [karelvuong/fox#15]
Hi, Thanks for Fox. I want to change the color for PHP (#ab7967) but I can't seem to make it take. Any suggestions? 

Image of part I tried changing:
http://t.co/HggOdPGiMK

Thanks.

**Comment by karelvuong** [comment]
@b-d-m-p: Odd, I'm not getting this issue on my side. Do you have the theme installed via Package Control? If you do, you're going to have to remove the package 'Theme - Fox' and clone it to your Packages folder off of GitHub.

This rule seems to affect the `<?php` tags and it took effect for me:

![screen shot 2015-02-05 at 4 37 16 pm](https://cloud.githubusercontent.com/assets/2213571/6072334/55f5f85a-ad55-11e4-896d-c0bc9258cc41.png)
![screen shot 2015-02-05 at 4 37 30 pm](https://cloud.githubusercontent.com/assets/2213571/6072335/55f6b092-ad55-11e4-8e1a-20fc6aa15f52.png)

**Comment by b-d-m-p** [comment]
Hi, Thanks.

I changed the php tag color, and you can see it taking affect here, but as soon as I pick the page, it switches to the old color. ( >_< ) Even after a restart. 

![screen shot 2015-02-06 at 10 02 47](https://cloud.githubusercontent.com/assets/1300390/6072654/6fda89ec-ade7-11e4-90b9-e341d73c59f1.png)

![screen shot 2015-02-06 at 10 02 53](https://cloud.githubusercontent.com/assets/1300390/6072659/784873fa-ade7-11e4-9ba0-257c85da33fe.png)

**Comment by karelvuong** [comment]
I believe the .phtml file is detected as HTML and is using that syntax instead of PHP. Try opening up the Command Palette `⌘+Shift+P` and type `Set Syntax: PHP`?

**Comment by b-d-m-p** [comment]
No go. :(

**Comment by karelvuong** [comment]
What does the folder structure that the fox.dark.tmTheme is stored in look like?

**Comment by b-d-m-p** [comment]
![screen shot 2015-02-06 at 10 08 49](https://cloud.githubusercontent.com/assets/1300390/6072721/2b22048c-ade8-11e4-90de-6ba21f7ad4e0.png)

**Comment by karelvuong** [comment]
That's really odd. Does the color revert back to its original in the file itself as well? Or only visibly on the code editor?

**Comment by b-d-m-p** [comment]
Just visibly.

**Comment by karelvuong** [comment]
How strange. It doesn't seem to be an issue for me as the change persists, but I'll see if I can recreate it. Thanks for reporting this Brett! :smiley:

**Comment by b-d-m-p** [comment]
Thanks for your help.

**Comment by b-d-m-p** [comment]
Thanks for making the theme. I really like it. The new FirefoxDeveloperEdition is really great. I don't know anyone that is using it though. Do you know how to give feedback to the developers?

**Comment by karelvuong** [comment]
You could try tweeting them at https://twitter.com/FirefoxDevTools.

**Comment by b-d-m-p** [comment]
Thanks. Will do. Keep up the good work. :)

**Comment by b-d-m-p** [comment]
Not sure why but it just started working yesterday. I didn't change anything to my knowledge. 

Thanks for your help.

**Comment by karelvuong** [comment]
That's a little odd but I'm happy to hear that! Going to close this issue now. :smile: 

Thanks again @b-d-m-p!
