### ISSUE TITLE
Find dialog input box and console background not themed

### ISSUE THREAD

**Issue by asampal** [karelvuong/fox#16]
I'm using Windows 8.1 64 bit, with Sublime Text 3 b3071

The background of the input box on the find dialog and the background of the console remain white with the dark theme applied. The effect is as if the theme is not finished. Is it meant to be white (light)?

**Comment by karelvuong** [comment]
@asampal: No, it's not meant to be white. Could you take a screenshot of it?

**Comment by asampal** [comment]
Here you go:
[console](http://imgur.com/0jJjc16)
[find](http://imgur.com/AXeNohe)

**Comment by karelvuong** [comment]
@asampal: All fixed! Please expect the update to propagate across Sublime Package Control soon! :smile:

**Comment by asampal** [comment]
Unfortunately the fix doesn't work for me - in fact it seems to affect the rest of the app even more. Note the not showing the sidebar, the artifacts under the menu and the console is still white. I tried completely removing and re-installing it, but got the same result.

[What happened?](http://imgur.com/Xg0kB0U)

**Comment by karelvuong** [comment]
Oh sorry! I forgot to tell you to rename the theme under your Settings to "Fox.sublime-theme.

**Comment by asampal** [comment]
OK, that seemed to do it - thanks. 

Don't forget to update the instructions on the PackageControl page. A couple more observations, though. Could you make the find text entry fields be darker like the Firefox console search entry box in the upper right (see [here](http://imgur.com/Bo8aQSl))? As well, the interior buffer background doesn't match the shade and darkness of the Firefox console main area for at least some file types where I would've expected it to (txt and Sublime Text settings (JSON, I guess)).
